site_name: Teleport 文档
copyright: TP4A Team.
site_author: Apex Liu
nav:
  - 首页: index.md
  - 安装&升级: install.md
  - 服务端配置:
    - 配置文件: config.md
    - Nginx配置: nginx.md
  - 用户手册:
     - 登录: guide_login.md
     - 资产管理: guide_asset.md
     - 用户管理: guide_user.md
     - 运维: guide_ops.md
     - 审计: guide_audit.md
     - 系统管理: guide_system.md
  - 客户端助手: assist.md
  - 开发手册: develop.md
  - 贡献者: contributor.md
  - 支持 Teleport: support.md
  - FAQ: faq.md

theme:
  name: null
  custom_dir: 'themes/readthedocs'
  static_templates:
    - 404.html

  include_search_page: true
  search_index_only: false

  highlightjs: true
  hljs_languages: []

markdown_extensions:
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - footnotes

repo_name: GitHub
repo_url: https://github.com/eomsoft/teleport
